version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install vapor/tap/vapor
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  linux:
    docker:
      - image: swift:4.0
    steps:
      - run: apt-get install -yq libssl-dev
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - macos
      - linux