name: deploy-api-docs
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
     uses: vapor/api-docs/.github/workflows/build-and-deploy-docs-workflow.yml@0cf3a0b827263a51af91ef402341222dcc48b098
     secrets: inherit
     with:
       package_name: vapor
       modules: Vapor,XCTVapor
       pathsToInvalidate: /vapor /xctvapor
