name: Generate Sponsors README
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get token
        id: get-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.PENNY_APP_ID }}
          private-key: ${{ secrets.PENNY_APP_PRIVATE_KEY }}

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ steps.get-token.outputs.token }}
          file: "README.md"
          minimum: 500
          maximum: 9900
          marker: "backers"
          organization: true

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.get-token.outputs.token }}
          commit-message: "[skip ci] Update README with new sponsor"
          committer: "Penny[bot] <360798+penny[bot]@vapor.codes>"
          author: "Penny[bot] <360798+penny[bot]@vapor.codes>"
          branch: update-sponsors
          delete-branch: true
          title: Update README with new sponsor
          body: Update README adding new sponsor
          labels: no-release-needed,sponsors
          reviewers: 0xTim
